# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('effect', models.TextField()),
                ('aura_range', models.IntegerField()),
                ('DC', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Senses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sense_range', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='alignment',
            field=models.CharField(choices=[('CE', 'Chaotic Evil'), ('CN', 'Chaotic Neutral'), ('CG', 'Chaotic Good'), ('NE', 'Neutral Evil'), ('TN', 'True Neutral'), ('NG', 'Neutral Good'), ('LE', 'Lawful Evil'), ('LN', 'Lawful Neutral'), ('LG', 'Lawful Good')], default='TN', max_length=2),
        ),
        migrations.AddField(
            model_name='creature',
            name='cr',
            field=models.CharField(choices=[('third', 'CR 1/3'), ('half', 'CR 1/2'), ('1', 'CR 1'), ('2', 'CR 2'), ('3', 'CR 3'), ('4', 'CR 4'), ('5', 'CR 5'), ('6', 'CR 6'), ('7', 'CR 7'), ('8', 'CR 8'), ('9', 'CR 9'), ('10', 'CR 10'), ('11', 'CR 11'), ('12', 'CR 12'), ('13', 'CR 13'), ('14', 'CR 14'), ('15', 'CR 15'), ('16', 'CR 16'), ('17', 'CR 17'), ('18', 'CR 18'), ('19', 'CR 19'), ('20', 'CR 20'), ('21', 'CR 21'), ('22', 'CR 22'), ('23', 'CR 23'), ('24', 'CR 24'), ('25', 'CR 25')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='creature',
            name='eac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='fortitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='kac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='race',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='reflex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='rp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='size',
            field=models.CharField(choices=[('F', 'Fine'), ('D', 'Diminutive'), ('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan'), ('C', 'Colossal')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='creature',
            name='will',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='creature',
            name='creature_class',
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creatureCreator.ClassGraft'),
        ),
        migrations.RemoveField(
            model_name='creature',
            name='creature_subtype',
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creatureCreator.CreatureSubtypeGraft'),
        ),
        migrations.RemoveField(
            model_name='creature',
            name='creature_template',
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creatureCreator.Template'),
        ),
        migrations.RemoveField(
            model_name='creature',
            name='creature_type',
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creatureCreator.CreatureTypeGraft'),
        ),
        migrations.AlterField(
            model_name='template',
            name='min_cr',
            field=models.CharField(choices=[('third', 'CR 1/3'), ('half', 'CR 1/2'), ('1', 'CR 1'), ('2', 'CR 2'), ('3', 'CR 3'), ('4', 'CR 4'), ('5', 'CR 5'), ('6', 'CR 6'), ('7', 'CR 7'), ('8', 'CR 8'), ('9', 'CR 9'), ('10', 'CR 10'), ('11', 'CR 11'), ('12', 'CR 12'), ('13', 'CR 13'), ('14', 'CR 14'), ('15', 'CR 15'), ('16', 'CR 16'), ('17', 'CR 17'), ('18', 'CR 18'), ('19', 'CR 19'), ('20', 'CR 20'), ('21', 'CR 21'), ('22', 'CR 22'), ('23', 'CR 23'), ('24', 'CR 24'), ('25', 'CR 25')], max_length=3),
        ),
        migrations.AddField(
            model_name='creature',
            name='aura',
            field=models.ManyToManyField(to='creatureCreator.Aura'),
        ),
        migrations.AddField(
            model_name='creature',
            name='senses',
            field=models.ManyToManyField(to='creatureCreator.Senses'),
        ),
    ]
