# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0002_auto_20180328_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='array',
        ),
        migrations.AddField(
            model_name='creature',
            name='array',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creatureCreator.Array'),
        ),
    ]
