# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0003_auto_20180329_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='creature',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='creature',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='creature',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='creature',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='creature',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
    ]
