# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0004_auto_20180331_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='array',
            old_name='spell_dc_base',
            new_name='base_spell_dc',
        ),
        migrations.AddField(
            model_name='array',
            name='four_melee_attack',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='array',
            name='high_attack_bonus',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='array',
            name='low_attack_bonus',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='array',
            name='ranged_energy_attack',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='array',
            name='ranged_kinetic_attack',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='array',
            name='standard_melee_attack',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='array',
            name='three_melee_attack',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='ability_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='base_spell_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='melee_attack',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='ranged_attack',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=False),
            preserve_default=False,
        ),
    ]
