# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 14:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0005_auto_20180331_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='melee_attack',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ranged_attack',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
