# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0006_auto_20180331_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creature',
            name='name',
            field=models.CharField(default='Creature Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='senses',
            name='subtype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
