# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatureCreator', '0008_auto_20180401_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialabilities',
            name='source',
            field=models.CharField(choices=[('URC', 'Universal Creature Rules'), ('FTS', 'Feats'), ('FRE', 'Free'), ('ADJ', 'Adjustment')], max_length=3, null=True),
        ),
    ]
